[package]
edition = "2021"
name = "detours-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.55"
lazy_static = "1.4.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
regex = "1.5.4"

re-utilities = {path = "../"}

[dependencies.syn]
features = ["full"]
version = "1.0.86"
