[package]
name = "detours-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.55"
regex = "1.5.4"
proc-macro2 = "1.0.36"
quote = "1.0.15"
lazy_static = "1.4.0"

re-utilities = { path = "../" }

[dependencies.syn]
version = "1.0.86"
features = ["full"]