[package]
name = "re-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
dll-syringe = "0.7.0"
# Temporary until https://github.com/EqualGames/game-scanner/pull/19 gets merged
game-scanner = { git = "https://github.com/philpax/game-scanner.git", branch = "fix-build-script" }

[dependencies.windows]
version = "0.33.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
]
