[package]
name = "re-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
syn = "1.0.89"
patternscan = "1.2.0"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }

[features]
debug-console = []

[target.'cfg(windows)'.dependencies]
detour = "0.8.1"
dll-syringe = "0.8.1"
game-scanner = "1.1.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.33.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
]
