[package]
name = "re-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
dll-syringe = "0.8.1"
game-scanner = "1.1.2"
patternscan = "1.2.0"

[features]
debug-console = []

[dependencies.windows]
version = "0.33.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
]
