[package]
name = "re-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
dll-syringe = "0.7.0"
game-scanner = "1.1.0"

[dependencies.windows]
version = "0.33.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
]
